(function(x){function m(b){this.options=q.extend({},m.defaultOptions,b);this.clear()}function e(b){this.options=q.extend({},e.defaultChartOptions,b);this.seriesSet=[];this.currentValueRange=1;this.lastRenderTimeMillis=this.currentVisMinValue=0}var q={extend:function(){arguments[0]=arguments[0]||{};for(var b=1;b<arguments.length;b++)for(var c in arguments[b])arguments[b].hasOwnProperty(c)&&(arguments[0][c]="object"===typeof arguments[b][c]?arguments[b][c]instanceof Array?arguments[b][c]:q.extend(arguments[0][c],
arguments[b][c]):arguments[b][c]);return arguments[0]}};m.defaultOptions={resetBoundsInterval:3E3,resetBounds:!0};m.prototype.clear=function(){this.data=[];this.minValue=this.maxValue=Number.NaN};m.prototype.resetBounds=function(){if(this.data.length){this.maxValue=this.data[0][1];this.minValue=this.data[0][1];for(var b=1;b<this.data.length;b++){var c=this.data[b][1];c>this.maxValue&&(this.maxValue=c);c<this.minValue&&(this.minValue=c)}}else this.minValue=this.maxValue=Number.NaN};m.prototype.append=
function(b,c,a){for(var h=this.data.length-1;0<=h&&this.data[h][0]>b;)h--; -1===h?this.data.splice(0,0,[b,c]):0<this.data.length&&this.data[h][0]===b?a?(this.data[h][1]+=c,c=this.data[h][1]):this.data[h][1]=c:h<this.data.length-1?this.data.splice(h+1,0,[b,c]):this.data.push([b,c]);this.maxValue=isNaN(this.maxValue)?c:Math.max(this.maxValue,c);this.minValue=isNaN(this.minValue)?c:Math.min(this.minValue,c)};m.prototype.dropOldData=function(b,c){for(var a=0;this.data.length-a>=c&&this.data[a+1][0]<b;)a++;
0!==a&&this.data.splice(0,a)};e.defaultChartOptions={millisPerPixel:20,enableDpiScaling:!0,yMinFormatter:function(b,c){return parseFloat(b).toFixed(c)},yMaxFormatter:function(b,c){return parseFloat(b).toFixed(c)},maxValueScale:1,minValueScale:1,interpolation:"bezier",scaleSmoothing:.125,maxDataSetLength:2,scrollBackwards:!1,grid:{fillStyle:"#000000",strokeStyle:"#777777",lineWidth:1,sharpLines:!1,millisPerLine:1E3,verticalSections:2,borderVisible:!0},labels:{fillStyle:"#ffffff",disabled:!1,fontSize:10,
fontFamily:"monospace",precision:2},horizontalLines:[]};e.AnimateCompatibility=function(){return{requestAnimationFrame:function(b,c){return(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){return window.setTimeout(function(){a((new Date).getTime())},16)}).call(window,b,c)},cancelAnimationFrame:function(b){return(window.cancelAnimationFrame||function(b){clearTimeout(b)}).call(window,
b)}}}();e.defaultSeriesPresentationOptions={lineWidth:1,strokeStyle:"#ffffff"};e.prototype.addTimeSeries=function(b,c){this.seriesSet.push({timeSeries:b,options:q.extend({},e.defaultSeriesPresentationOptions,c)});b.options.resetBounds&&0<b.options.resetBoundsInterval&&(b.resetBoundsTimerId=setInterval(function(){b.resetBounds()},b.options.resetBoundsInterval))};e.prototype.removeTimeSeries=function(b){for(var c=this.seriesSet.length,a=0;a<c;a++)if(this.seriesSet[a].timeSeries===b){this.seriesSet.splice(a,
1);break}b.resetBoundsTimerId&&clearInterval(b.resetBoundsTimerId)};e.prototype.getTimeSeriesOptions=function(b){for(var c=this.seriesSet.length,a=0;a<c;a++)if(this.seriesSet[a].timeSeries===b)return this.seriesSet[a].options};e.prototype.bringToFront=function(b){for(var c=this.seriesSet.length,a=0;a<c;a++)if(this.seriesSet[a].timeSeries===b){b=this.seriesSet.splice(a,1);this.seriesSet.push(b[0]);break}};e.prototype.streamTo=function(b,c){this.canvas=b;this.delay=c;this.start()};e.prototype.resize=
function(){if(this.options.enableDpiScaling&&window&&1!==window.devicePixelRatio){var b=window.devicePixelRatio,c=parseInt(this.canvas.getAttribute("width")),a=parseInt(this.canvas.getAttribute("height"));this.originalWidth&&Math.floor(this.originalWidth*b)===c||(this.originalWidth=c,this.canvas.setAttribute("width",Math.floor(c*b).toString()),this.canvas.style.width=c+"px",this.canvas.getContext("2d").scale(b,b));this.originalHeight&&Math.floor(this.originalHeight*b)===a||(this.originalHeight=a,
this.canvas.setAttribute("height",Math.floor(a*b).toString()),this.canvas.style.height=a+"px",this.canvas.getContext("2d").scale(b,b))}};e.prototype.start=function(){if(!this.frame){var b=function(){this.frame=e.AnimateCompatibility.requestAnimationFrame(function(){this.render();b()}.bind(this))}.bind(this);b()}};e.prototype.stop=function(){this.frame&&(e.AnimateCompatibility.cancelAnimationFrame(this.frame),delete this.frame)};e.prototype.updateValueRange=function(){for(var b=this.options,c=Number.NaN,
a=Number.NaN,h=0;h<this.seriesSet.length;h++){var d=this.seriesSet[h].timeSeries;isNaN(d.maxValue)||(c=isNaN(c)?d.maxValue:Math.max(c,d.maxValue));isNaN(d.minValue)||(a=isNaN(a)?d.minValue:Math.min(a,d.minValue))}c=null!=b.maxValue?b.maxValue:c*b.maxValueScale;a=null!=b.minValue?b.minValue:a-Math.abs(a*b.minValueScale-a);this.options.yRangeFunction&&(c=this.options.yRangeFunction({min:a,max:c}),a=c.min,c=c.max);isNaN(c)||isNaN(a)||(h=c-a-this.currentValueRange,d=a-this.currentVisMinValue,this.isAnimatingScale=
.1<Math.abs(h)||.1<Math.abs(d),this.currentValueRange+=b.scaleSmoothing*h,this.currentVisMinValue+=b.scaleSmoothing*d);this.valueRange={min:a,max:c}};e.prototype.render=function(b,c){var a=(new Date).getTime();if(!this.isAnimatingScale){var h=Math.min(1E3/6,this.options.millisPerPixel);if(a-this.lastRenderTimeMillis<h)return}this.resize();this.lastRenderTimeMillis=a;b=b||this.canvas;c=c||a-(this.delay||0);c-=c%this.options.millisPerPixel;var a=b.getContext("2d"),d=this.options,e=b.clientWidth,l=b.clientHeight,
h=c-e*d.millisPerPixel,n=function(a){a-=this.currentVisMinValue;return 0===this.currentValueRange?l:l-Math.round(a/this.currentValueRange*l)}.bind(this),m=function(a){return d.scrollBackwards?Math.round((c-a)/d.millisPerPixel):Math.round(e-(c-a)/d.millisPerPixel)};this.updateValueRange();a.font=d.labels.fontSize+"px "+d.labels.fontFamily;a.save();a.translate(0,0);a.beginPath();a.rect(0,0,e,l);a.clip();a.save();a.fillStyle=d.grid.fillStyle;a.clearRect(0,0,e,l);a.fillRect(0,0,e,l);a.restore();a.save();
a.lineWidth=d.grid.lineWidth;a.strokeStyle=d.grid.strokeStyle;if(0<d.grid.millisPerLine){a.beginPath();for(var f=c-c%d.grid.millisPerLine;f>=h;f-=d.grid.millisPerLine){var g=m(f);d.grid.sharpLines&&(g-=.5);a.moveTo(g,0);a.lineTo(g,l)}a.stroke();a.closePath()}for(f=1;f<d.grid.verticalSections;f++)g=Math.round(f*l/d.grid.verticalSections),d.grid.sharpLines&&(g-=.5),a.beginPath(),a.moveTo(0,g),a.lineTo(e,g),a.stroke(),a.closePath();d.grid.borderVisible&&(a.beginPath(),a.strokeRect(0,0,e,l),a.closePath());
a.restore();if(d.horizontalLines&&d.horizontalLines.length)for(f=0;f<d.horizontalLines.length;f++){var g=d.horizontalLines[f],k=Math.round(n(g.value))-.5;a.strokeStyle=g.color||"#ffffff";a.lineWidth=g.lineWidth||1;a.beginPath();a.moveTo(0,k);a.lineTo(e,k);a.stroke();a.closePath()}for(f=0;f<this.seriesSet.length;f++){a.save();var u=this.seriesSet[f].timeSeries,g=u.data,k=this.seriesSet[f].options;u.dropOldData(h,d.maxDataSetLength);a.lineWidth=k.lineWidth;a.strokeStyle=k.strokeStyle;a.beginPath();
for(var q=u=0,w=0,v=0;v<g.length&&1!==g.length;v++){var p=m(g[v][0]),t=n(g[v][1]);if(0===v)u=p,a.moveTo(p,t);else switch(d.interpolation){case "linear":case "line":a.lineTo(p,t);break;default:a.bezierCurveTo(Math.round((q+p)/2),w,Math.round(q+p)/2,t,p,t);break;case "step":a.lineTo(p,w),a.lineTo(p,t)}q=p;w=t}1<g.length&&(k.fillStyle&&(a.lineTo(e+k.lineWidth+1,w),a.lineTo(e+k.lineWidth+1,l+k.lineWidth+1),a.lineTo(u,l+k.lineWidth),a.fillStyle=k.fillStyle,a.fill()),k.strokeStyle&&"none"!==k.strokeStyle&&
a.stroke(),a.closePath());a.restore()}if(!d.labels.disabled&&!isNaN(this.valueRange.min)&&!isNaN(this.valueRange.max)){var n=d.yMaxFormatter(this.valueRange.max,d.labels.precision),r=d.yMinFormatter(this.valueRange.min,d.labels.precision),f=d.scrollBackwards?0:e-a.measureText(n).width-2;a.fillStyle=d.labels.fillStyle;a.fillText(n,f,d.labels.fontSize);a.fillText(r,f,l-2)}if(d.timestampFormatter&&0<d.grid.millisPerLine)for(r=d.scrollBackwards?a.measureText(r).width:e-a.measureText(r).width+4,f=c-c%
d.grid.millisPerLine;f>=h;f-=d.grid.millisPerLine)if(g=m(f),!d.scrollBackwards&&g<r||d.scrollBackwards&&g>r)n=d.timestampFormatter(new Date(f)),k=a.measureText(n).width,r=d.scrollBackwards?g+k+2:g-k-2,a.fillStyle=d.labels.fillStyle,d.scrollBackwards?a.fillText(n,g,l-2):a.fillText(n,g-k,l-2);a.restore()};e.timeFormatter=function(b){function c(a){return(10>a?"0":"")+a}return c(b.getHours())+":"+c(b.getMinutes())+":"+c(b.getSeconds())};x.TimeSeries=m;x.SmoothieChart=e})("undefined"===typeof exports?
this:exports);